/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearlyRouteImport } from './routes/yearly'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const YearlyRoute = YearlyRouteImport.update({
  id: '/yearly',
  path: '/yearly',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/manage': typeof ManageRoute
  '/meetings': typeof MeetingsRoute
  '/weekly': typeof WeeklyRoute
  '/yearly': typeof YearlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/manage': typeof ManageRoute
  '/meetings': typeof MeetingsRoute
  '/weekly': typeof WeeklyRoute
  '/yearly': typeof YearlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/manage': typeof ManageRoute
  '/meetings': typeof MeetingsRoute
  '/weekly': typeof WeeklyRoute
  '/yearly': typeof YearlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/manage' | '/meetings' | '/weekly' | '/yearly'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/manage' | '/meetings' | '/weekly' | '/yearly'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/manage'
    | '/meetings'
    | '/weekly'
    | '/yearly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ManageRoute: typeof ManageRoute
  MeetingsRoute: typeof MeetingsRoute
  WeeklyRoute: typeof WeeklyRoute
  YearlyRoute: typeof YearlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yearly': {
      id: '/yearly'
      path: '/yearly'
      fullPath: '/yearly'
      preLoaderRoute: typeof YearlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ManageRoute: ManageRoute,
  MeetingsRoute: MeetingsRoute,
  WeeklyRoute: WeeklyRoute,
  YearlyRoute: YearlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
